[package]
name = "yunpao"
version = "0.1.2"
description = "Remote Session and Task Manager"
edition = "2024"
license-file = "LICENSE"
authors = ["Alex Karev <alexkarev@sjtu.edu.cn>"]
keywords = ["cli", "linux", "workflow", "machine-learning"]
categories = ["command-line-utilities", "development-tools"]
repository = "https://github.com/alex-karev/yunpao"
readme = "README.md"

[dependencies]
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.7", features = ["derive"] }
cliclack = "0.5.6"
colored = "3.1.1"
ctrlc = "3.5.2"
derive = "1.0.0"
dirs = "7.0.0"
dotenvy = "0.15.7"
edit = "0.1.5"
log = { version = "0.4.34", features = ["std"]}
serde = { version = "1.0.229", features = ["derive"] }
shellexpand = "3.1.2"
toml = "1.1.6"
uuid = { version = "1.26.1", features = ["v4"] }
